


CREATE TABLE TAB1(
    C1 NUMBER,
    C2 NUMBER,
    C3 VARCHAR2(1)
);

INSERT INTO TAB1 VALUES(1, NULL, 'A');
INSERT INTO TAB1 VALUES(2, 1, 'B');
INSERT INTO TAB1 VALUES(3, 1, 'C');
INSERT INTO TAB1 VALUES(4, 2, 'D');


SELECT C3
FROM TAB1
START WITH C2 IS NULL
CONNECT BY PRIOR C1 = C2
;

ORDER SIBLINGS BY C3 DESC;

